/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GithubRouteRouteImport } from './routes/_github/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubOwnerRouteImport } from './routes/_github/$owner'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GithubOwnerRepoRouteRouteImport } from './routes/_github/$owner_.$repo/route'
import { Route as GithubOwnerRepoIndexRouteImport } from './routes/_github/$owner_.$repo/index'
import { Route as GithubOwnerRepoPrIndexRouteImport } from './routes/_github/$owner_.$repo/pr/index'
import { Route as GithubOwnerRepoIssuesIndexRouteImport } from './routes/_github/$owner_.$repo/issues/index'
import { Route as GithubOwnerRepoChatIndexRouteImport } from './routes/_github/$owner_.$repo/chat/index'
import { Route as GithubOwnerRepoArchIndexRouteImport } from './routes/_github/$owner_.$repo/arch/index'
import { Route as GithubOwnerRepoPrNumberRouteImport } from './routes/_github/$owner_.$repo/pr/$number'
import { Route as GithubOwnerRepoIssuesNumberRouteImport } from './routes/_github/$owner_.$repo/issues/$number'
import { Route as GithubOwnerRepoArchEntrypointRouteImport } from './routes/_github/$owner_.$repo/arch/$entrypoint'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRouteRoute = GithubRouteRouteImport.update({
  id: '/_github',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubOwnerRoute = GithubOwnerRouteImport.update({
  id: '/$owner',
  path: '/$owner',
  getParentRoute: () => GithubRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubOwnerRepoRouteRoute = GithubOwnerRepoRouteRouteImport.update({
  id: '/$owner_/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => GithubRouteRoute,
} as any)
const GithubOwnerRepoIndexRoute = GithubOwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GithubOwnerRepoRouteRoute,
} as any)
const GithubOwnerRepoPrIndexRoute = GithubOwnerRepoPrIndexRouteImport.update({
  id: '/pr/',
  path: '/pr/',
  getParentRoute: () => GithubOwnerRepoRouteRoute,
} as any)
const GithubOwnerRepoIssuesIndexRoute =
  GithubOwnerRepoIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => GithubOwnerRepoRouteRoute,
  } as any)
const GithubOwnerRepoChatIndexRoute =
  GithubOwnerRepoChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => GithubOwnerRepoRouteRoute,
  } as any)
const GithubOwnerRepoArchIndexRoute =
  GithubOwnerRepoArchIndexRouteImport.update({
    id: '/arch/',
    path: '/arch/',
    getParentRoute: () => GithubOwnerRepoRouteRoute,
  } as any)
const GithubOwnerRepoPrNumberRoute = GithubOwnerRepoPrNumberRouteImport.update({
  id: '/pr/$number',
  path: '/pr/$number',
  getParentRoute: () => GithubOwnerRepoRouteRoute,
} as any)
const GithubOwnerRepoIssuesNumberRoute =
  GithubOwnerRepoIssuesNumberRouteImport.update({
    id: '/issues/$number',
    path: '/issues/$number',
    getParentRoute: () => GithubOwnerRepoRouteRoute,
  } as any)
const GithubOwnerRepoArchEntrypointRoute =
  GithubOwnerRepoArchEntrypointRouteImport.update({
    id: '/arch/$entrypoint',
    path: '/arch/$entrypoint',
    getParentRoute: () => GithubOwnerRepoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/$owner': typeof GithubOwnerRoute
  '/$owner/$repo': typeof GithubOwnerRepoRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$owner/$repo/': typeof GithubOwnerRepoIndexRoute
  '/$owner/$repo/arch/$entrypoint': typeof GithubOwnerRepoArchEntrypointRoute
  '/$owner/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/$owner/$repo/pr/$number': typeof GithubOwnerRepoPrNumberRoute
  '/$owner/$repo/arch': typeof GithubOwnerRepoArchIndexRoute
  '/$owner/$repo/chat': typeof GithubOwnerRepoChatIndexRoute
  '/$owner/$repo/issues': typeof GithubOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pr': typeof GithubOwnerRepoPrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/$owner': typeof GithubOwnerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$owner/$repo': typeof GithubOwnerRepoIndexRoute
  '/$owner/$repo/arch/$entrypoint': typeof GithubOwnerRepoArchEntrypointRoute
  '/$owner/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/$owner/$repo/pr/$number': typeof GithubOwnerRepoPrNumberRoute
  '/$owner/$repo/arch': typeof GithubOwnerRepoArchIndexRoute
  '/$owner/$repo/chat': typeof GithubOwnerRepoChatIndexRoute
  '/$owner/$repo/issues': typeof GithubOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pr': typeof GithubOwnerRepoPrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_github': typeof GithubRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/_github/$owner': typeof GithubOwnerRoute
  '/_github/$owner_/$repo': typeof GithubOwnerRepoRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_github/$owner_/$repo/': typeof GithubOwnerRepoIndexRoute
  '/_github/$owner_/$repo/arch/$entrypoint': typeof GithubOwnerRepoArchEntrypointRoute
  '/_github/$owner_/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/_github/$owner_/$repo/pr/$number': typeof GithubOwnerRepoPrNumberRoute
  '/_github/$owner_/$repo/arch/': typeof GithubOwnerRepoArchIndexRoute
  '/_github/$owner_/$repo/chat/': typeof GithubOwnerRepoChatIndexRoute
  '/_github/$owner_/$repo/issues/': typeof GithubOwnerRepoIssuesIndexRoute
  '/_github/$owner_/$repo/pr/': typeof GithubOwnerRepoPrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/sign-in'
    | '/$owner'
    | '/$owner/$repo'
    | '/api/auth/$'
    | '/$owner/$repo/'
    | '/$owner/$repo/arch/$entrypoint'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pr/$number'
    | '/$owner/$repo/arch'
    | '/$owner/$repo/chat'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/sign-in'
    | '/$owner'
    | '/api/auth/$'
    | '/$owner/$repo'
    | '/$owner/$repo/arch/$entrypoint'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pr/$number'
    | '/$owner/$repo/arch'
    | '/$owner/$repo/chat'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pr'
  id:
    | '__root__'
    | '/'
    | '/_github'
    | '/about'
    | '/explore'
    | '/sign-in'
    | '/_github/$owner'
    | '/_github/$owner_/$repo'
    | '/api/auth/$'
    | '/_github/$owner_/$repo/'
    | '/_github/$owner_/$repo/arch/$entrypoint'
    | '/_github/$owner_/$repo/issues/$number'
    | '/_github/$owner_/$repo/pr/$number'
    | '/_github/$owner_/$repo/arch/'
    | '/_github/$owner_/$repo/chat/'
    | '/_github/$owner_/$repo/issues/'
    | '/_github/$owner_/$repo/pr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubRouteRoute: typeof GithubRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_github': {
      id: '/_github'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GithubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_github/$owner': {
      id: '/_github/$owner'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof GithubOwnerRouteImport
      parentRoute: typeof GithubRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_github/$owner_/$repo': {
      id: '/_github/$owner_/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof GithubOwnerRepoRouteRouteImport
      parentRoute: typeof GithubRouteRoute
    }
    '/_github/$owner_/$repo/': {
      id: '/_github/$owner_/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof GithubOwnerRepoIndexRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/pr/': {
      id: '/_github/$owner_/$repo/pr/'
      path: '/pr'
      fullPath: '/$owner/$repo/pr'
      preLoaderRoute: typeof GithubOwnerRepoPrIndexRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/issues/': {
      id: '/_github/$owner_/$repo/issues/'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof GithubOwnerRepoIssuesIndexRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/chat/': {
      id: '/_github/$owner_/$repo/chat/'
      path: '/chat'
      fullPath: '/$owner/$repo/chat'
      preLoaderRoute: typeof GithubOwnerRepoChatIndexRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/arch/': {
      id: '/_github/$owner_/$repo/arch/'
      path: '/arch'
      fullPath: '/$owner/$repo/arch'
      preLoaderRoute: typeof GithubOwnerRepoArchIndexRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/pr/$number': {
      id: '/_github/$owner_/$repo/pr/$number'
      path: '/pr/$number'
      fullPath: '/$owner/$repo/pr/$number'
      preLoaderRoute: typeof GithubOwnerRepoPrNumberRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/issues/$number': {
      id: '/_github/$owner_/$repo/issues/$number'
      path: '/issues/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof GithubOwnerRepoIssuesNumberRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
    '/_github/$owner_/$repo/arch/$entrypoint': {
      id: '/_github/$owner_/$repo/arch/$entrypoint'
      path: '/arch/$entrypoint'
      fullPath: '/$owner/$repo/arch/$entrypoint'
      preLoaderRoute: typeof GithubOwnerRepoArchEntrypointRouteImport
      parentRoute: typeof GithubOwnerRepoRouteRoute
    }
  }
}

interface GithubOwnerRepoRouteRouteChildren {
  GithubOwnerRepoIndexRoute: typeof GithubOwnerRepoIndexRoute
  GithubOwnerRepoArchEntrypointRoute: typeof GithubOwnerRepoArchEntrypointRoute
  GithubOwnerRepoIssuesNumberRoute: typeof GithubOwnerRepoIssuesNumberRoute
  GithubOwnerRepoPrNumberRoute: typeof GithubOwnerRepoPrNumberRoute
  GithubOwnerRepoArchIndexRoute: typeof GithubOwnerRepoArchIndexRoute
  GithubOwnerRepoChatIndexRoute: typeof GithubOwnerRepoChatIndexRoute
  GithubOwnerRepoIssuesIndexRoute: typeof GithubOwnerRepoIssuesIndexRoute
  GithubOwnerRepoPrIndexRoute: typeof GithubOwnerRepoPrIndexRoute
}

const GithubOwnerRepoRouteRouteChildren: GithubOwnerRepoRouteRouteChildren = {
  GithubOwnerRepoIndexRoute: GithubOwnerRepoIndexRoute,
  GithubOwnerRepoArchEntrypointRoute: GithubOwnerRepoArchEntrypointRoute,
  GithubOwnerRepoIssuesNumberRoute: GithubOwnerRepoIssuesNumberRoute,
  GithubOwnerRepoPrNumberRoute: GithubOwnerRepoPrNumberRoute,
  GithubOwnerRepoArchIndexRoute: GithubOwnerRepoArchIndexRoute,
  GithubOwnerRepoChatIndexRoute: GithubOwnerRepoChatIndexRoute,
  GithubOwnerRepoIssuesIndexRoute: GithubOwnerRepoIssuesIndexRoute,
  GithubOwnerRepoPrIndexRoute: GithubOwnerRepoPrIndexRoute,
}

const GithubOwnerRepoRouteRouteWithChildren =
  GithubOwnerRepoRouteRoute._addFileChildren(GithubOwnerRepoRouteRouteChildren)

interface GithubRouteRouteChildren {
  GithubOwnerRoute: typeof GithubOwnerRoute
  GithubOwnerRepoRouteRoute: typeof GithubOwnerRepoRouteRouteWithChildren
}

const GithubRouteRouteChildren: GithubRouteRouteChildren = {
  GithubOwnerRoute: GithubOwnerRoute,
  GithubOwnerRepoRouteRoute: GithubOwnerRepoRouteRouteWithChildren,
}

const GithubRouteRouteWithChildren = GithubRouteRoute._addFileChildren(
  GithubRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubRouteRoute: GithubRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
