/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestWorkflowRouteImport } from './routes/test-workflow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestWorkflowRoute = TestWorkflowRouteImport.update({
  id: '/test-workflow',
  path: '/test-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/test-workflow': typeof TestWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/test-workflow': typeof TestWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRoute
  '/dashboard': typeof DashboardRoute
  '/test-workflow': typeof TestWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/test-workflow'
    | '/api/auth/$'
    | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/test-workflow'
    | '/api/auth/$'
    | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/dashboard'
    | '/test-workflow'
    | '/api/auth/$'
    | '/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRoute
  DashboardRoute: typeof DashboardRoute
  TestWorkflowRoute: typeof TestWorkflowRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-workflow': {
      id: '/test-workflow'
      path: '/test-workflow'
      fullPath: '/test-workflow'
      preLoaderRoute: typeof TestWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRoute,
  DashboardRoute: DashboardRoute,
  TestWorkflowRoute: TestWorkflowRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
